<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.BTNAboutThisApplication = New System.Windows.Forms.Button()
        Me.PictureBox1 = New System.Windows.Forms.PictureBox()
        Me.ExitButton = New System.Windows.Forms.Button()
        Me.Browse = New System.Windows.Forms.Button()
        Me.BTNSignIn = New System.Windows.Forms.Button()
        Me.PictureBox2 = New System.Windows.Forms.PictureBox()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Panel1 = New System.Windows.Forms.Panel()
        Me.Label9 = New System.Windows.Forms.Label()
        Me.PictureBox3 = New System.Windows.Forms.PictureBox()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.Label8 = New System.Windows.Forms.Label()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label10 = New System.Windows.Forms.Label()
        Me.Button1 = New System.Windows.Forms.Button()
        Me.Button2 = New System.Windows.Forms.Button()
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.Panel1.SuspendLayout()
        CType(Me.PictureBox3, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'BTNAboutThisApplication
        '
        Me.BTNAboutThisApplication.BackgroundImage = CType(resources.GetObject("BTNAboutThisApplication.BackgroundImage"), System.Drawing.Image)
        Me.BTNAboutThisApplication.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.BTNAboutThisApplication.Location = New System.Drawing.Point(895, 578)
        Me.BTNAboutThisApplication.Name = "BTNAboutThisApplication"
        Me.BTNAboutThisApplication.Size = New System.Drawing.Size(123, 59)
        Me.BTNAboutThisApplication.TabIndex = 0
        Me.BTNAboutThisApplication.Text = "Software Details"
        Me.BTNAboutThisApplication.UseVisualStyleBackColor = True
        '
        'PictureBox1
        '
        Me.PictureBox1.BackgroundImage = CType(resources.GetObject("PictureBox1.BackgroundImage"), System.Drawing.Image)
        Me.PictureBox1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D
        Me.PictureBox1.Location = New System.Drawing.Point(0, 0)
        Me.PictureBox1.Name = "PictureBox1"
        Me.PictureBox1.Size = New System.Drawing.Size(235, 143)
        Me.PictureBox1.TabIndex = 2
        Me.PictureBox1.TabStop = False
        '
        'ExitButton
        '
        Me.ExitButton.BackgroundImage = CType(resources.GetObject("ExitButton.BackgroundImage"), System.Drawing.Image)
        Me.ExitButton.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.ExitButton.Location = New System.Drawing.Point(1049, 578)
        Me.ExitButton.Name = "ExitButton"
        Me.ExitButton.Size = New System.Drawing.Size(123, 59)
        Me.ExitButton.TabIndex = 3
        Me.ExitButton.Text = "Exit "
        Me.ExitButton.UseVisualStyleBackColor = True
        '
        'Browse
        '
        Me.Browse.BackgroundImage = CType(resources.GetObject("Browse.BackgroundImage"), System.Drawing.Image)
        Me.Browse.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Browse.Location = New System.Drawing.Point(895, 441)
        Me.Browse.Name = "Browse"
        Me.Browse.Size = New System.Drawing.Size(189, 52)
        Me.Browse.TabIndex = 4
        Me.Browse.Text = "Open in webpage"
        Me.Browse.UseVisualStyleBackColor = True
        '
        'BTNSignIn
        '
        Me.BTNSignIn.BackgroundImage = CType(resources.GetObject("BTNSignIn.BackgroundImage"), System.Drawing.Image)
        Me.BTNSignIn.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.BTNSignIn.Location = New System.Drawing.Point(1020, 157)
        Me.BTNSignIn.Name = "BTNSignIn"
        Me.BTNSignIn.Size = New System.Drawing.Size(161, 50)
        Me.BTNSignIn.TabIndex = 5
        Me.BTNSignIn.Text = "Sign In"
        Me.BTNSignIn.UseVisualStyleBackColor = True
        '
        'PictureBox2
        '
        Me.PictureBox2.BackgroundImage = CType(resources.GetObject("PictureBox2.BackgroundImage"), System.Drawing.Image)
        Me.PictureBox2.Location = New System.Drawing.Point(1020, 12)
        Me.PictureBox2.Name = "PictureBox2"
        Me.PictureBox2.Size = New System.Drawing.Size(161, 151)
        Me.PictureBox2.TabIndex = 6
        Me.PictureBox2.TabStop = False
        '
        'Label1
        '
        Me.Label1.BackColor = System.Drawing.SystemColors.ActiveCaption
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label1.Location = New System.Drawing.Point(147, 32)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(158, 36)
        Me.Label1.TabIndex = 7
        Me.Label1.Text = "Buying History :"
        '
        'Panel1
        '
        Me.Panel1.BackColor = System.Drawing.SystemColors.ActiveCaption
        Me.Panel1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D
        Me.Panel1.Controls.Add(Me.Label9)
        Me.Panel1.Controls.Add(Me.PictureBox3)
        Me.Panel1.Controls.Add(Me.Label1)
        Me.Panel1.Controls.Add(Me.Label6)
        Me.Panel1.Controls.Add(Me.Label7)
        Me.Panel1.Controls.Add(Me.Label8)
        Me.Panel1.Controls.Add(Me.Label5)
        Me.Panel1.Controls.Add(Me.Label4)
        Me.Panel1.Controls.Add(Me.Label3)
        Me.Panel1.Controls.Add(Me.Label2)
        Me.Panel1.Location = New System.Drawing.Point(12, 189)
        Me.Panel1.Name = "Panel1"
        Me.Panel1.Size = New System.Drawing.Size(877, 448)
        Me.Panel1.TabIndex = 8
        '
        'Label9
        '
        Me.Label9.BackColor = System.Drawing.Color.Transparent
        Me.Label9.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label9.Location = New System.Drawing.Point(11, 362)
        Me.Label9.Name = "Label9"
        Me.Label9.Size = New System.Drawing.Size(294, 62)
        Me.Label9.TabIndex = 17
        Me.Label9.Text = "ITEM IMAGE AND DESCRIPTION"
        '
        'PictureBox3
        '
        Me.PictureBox3.BackgroundImage = CType(resources.GetObject("PictureBox3.BackgroundImage"), System.Drawing.Image)
        Me.PictureBox3.Location = New System.Drawing.Point(16, 87)
        Me.PictureBox3.Name = "PictureBox3"
        Me.PictureBox3.Size = New System.Drawing.Size(289, 257)
        Me.PictureBox3.TabIndex = 16
        Me.PictureBox3.TabStop = False
        '
        'Label6
        '
        Me.Label6.BackColor = System.Drawing.Color.White
        Me.Label6.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label6.Location = New System.Drawing.Point(330, 401)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(516, 23)
        Me.Label6.TabIndex = 15
        Me.Label6.Text = "None..."
        '
        'Label7
        '
        Me.Label7.BackColor = System.Drawing.Color.White
        Me.Label7.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label7.Location = New System.Drawing.Point(330, 339)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(516, 23)
        Me.Label7.TabIndex = 14
        Me.Label7.Text = "None..."
        '
        'Label8
        '
        Me.Label8.BackColor = System.Drawing.Color.White
        Me.Label8.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label8.Location = New System.Drawing.Point(330, 279)
        Me.Label8.Name = "Label8"
        Me.Label8.Size = New System.Drawing.Size(516, 23)
        Me.Label8.TabIndex = 13
        Me.Label8.Text = "None..."
        '
        'Label5
        '
        Me.Label5.BackColor = System.Drawing.Color.White
        Me.Label5.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label5.Location = New System.Drawing.Point(330, 220)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(516, 23)
        Me.Label5.TabIndex = 12
        Me.Label5.Text = "None..."
        '
        'Label4
        '
        Me.Label4.BackColor = System.Drawing.Color.White
        Me.Label4.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label4.Location = New System.Drawing.Point(330, 158)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(516, 23)
        Me.Label4.TabIndex = 11
        Me.Label4.Text = "None..."
        '
        'Label3
        '
        Me.Label3.BackColor = System.Drawing.Color.White
        Me.Label3.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label3.Location = New System.Drawing.Point(330, 98)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(516, 23)
        Me.Label3.TabIndex = 10
        Me.Label3.Text = "None..."
        '
        'Label2
        '
        Me.Label2.BackColor = System.Drawing.Color.White
        Me.Label2.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Label2.Location = New System.Drawing.Point(330, 32)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(516, 23)
        Me.Label2.TabIndex = 9
        Me.Label2.Text = "None..."
        '
        'Label10
        '
        Me.Label10.BackColor = System.Drawing.Color.Transparent
        Me.Label10.Font = New System.Drawing.Font("Microsoft Sans Serif", 25.0!)
        Me.Label10.Location = New System.Drawing.Point(237, 21)
        Me.Label10.Name = "Label10"
        Me.Label10.Size = New System.Drawing.Size(777, 96)
        Me.Label10.TabIndex = 10
        Me.Label10.Text = "PC HEAVEN ONLINE PARTS PLATFORM"
        Me.Label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        '
        'Button1
        '
        Me.Button1.BackgroundImage = CType(resources.GetObject("Button1.BackgroundImage"), System.Drawing.Image)
        Me.Button1.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Button1.Location = New System.Drawing.Point(895, 501)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(189, 52)
        Me.Button1.TabIndex = 11
        Me.Button1.Text = "Report Issue"
        Me.Button1.UseVisualStyleBackColor = True
        '
        'Button2
        '
        Me.Button2.BackgroundImage = CType(resources.GetObject("Button2.BackgroundImage"), System.Drawing.Image)
        Me.Button2.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.0!)
        Me.Button2.Location = New System.Drawing.Point(895, 377)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(189, 57)
        Me.Button2.TabIndex = 12
        Me.Button2.Text = "Latest Item"
        Me.Button2.UseVisualStyleBackColor = True
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackgroundImage = CType(resources.GetObject("$this.BackgroundImage"), System.Drawing.Image)
        Me.ClientSize = New System.Drawing.Size(1184, 649)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.Label10)
        Me.Controls.Add(Me.PictureBox2)
        Me.Controls.Add(Me.BTNSignIn)
        Me.Controls.Add(Me.Browse)
        Me.Controls.Add(Me.ExitButton)
        Me.Controls.Add(Me.PictureBox1)
        Me.Controls.Add(Me.BTNAboutThisApplication)
        Me.Controls.Add(Me.Panel1)
        Me.Name = "Form1"
        Me.Text = "Form1"
        CType(Me.PictureBox1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.PictureBox2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.Panel1.ResumeLayout(False)
        CType(Me.PictureBox3, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents BTNAboutThisApplication As Button
    Friend WithEvents PictureBox1 As PictureBox
    Friend WithEvents ExitButton As Button
    Friend WithEvents Browse As Button
    Friend WithEvents BTNSignIn As Button
    Friend WithEvents PictureBox2 As PictureBox
    Friend WithEvents Label1 As Label
    Friend WithEvents Panel1 As Panel
    Friend WithEvents Label9 As Label
    Friend WithEvents PictureBox3 As PictureBox
    Friend WithEvents Label6 As Label
    Friend WithEvents Label7 As Label
    Friend WithEvents Label8 As Label
    Friend WithEvents Label5 As Label
    Friend WithEvents Label4 As Label
    Friend WithEvents Label3 As Label
    Friend WithEvents Label2 As Label
    Friend WithEvents Label10 As Label
    Friend WithEvents Button1 As Button
    Friend WithEvents Button2 As Button
End Class
